# Generated by Django 2.1.5 on 2020-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('first_Name', models.CharField(max_length=500)),
                ('last_Name', models.CharField(max_length=500)),
                ('Dob', models.DateField()),
                ('authorized', models.CharField(default='N', max_length=20)),
                ('user_since', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Y', max_length=500)),
                ('weight', models.FloatField(max_length=10)),
                ('photo', models.ImageField(upload_to='authentication/media/%Y/%m/%d/')),
            ],
        ),
    ]
